name: Test & Deploy

on: [push]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "CICD running"
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run Utility Tests
        run: npm test utils
      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: nc_games_test
          postgresql user: george
          postgresql password: worsnop
      - name: Run Integration Tests
        run: PGDATABASE=nc_games_test PGUSER=george PGPASSWORD=worsnop npm test app
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2
      - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_api_email: ${{secrets.HEROKU_EMAIL}}
